require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./models/User');
const PartnerProfile = require('./models/PartnerProfile');

mongoose.connect(process.env.MONGO_URI)
    .then(() => console.log('MongoDB Connected'))
    .catch(err => console.error(err));

const indianPartners = [
    {
        email: "taj.palace.delhi@example.com",
        password: "partner123",
        companyName: "The Taj Palace Delhi",
        destinations: ["Delhi", "New Delhi"],
        type: "Hotel",
        specializations: ["Luxury", "Heritage", "Business"],
        budgetRange: { min: 15000, max: 45000 },
        rating: 5,
        description: "An iconic luxury hotel in the heart of India's capital, The Taj Palace Delhi offers world-class hospitality with stunning views of the city. Experience regal comfort with modern amenities, Michelin-starred dining, and impeccable service.",
        amenities: ["Rooftop Pool", "Jiva Spa", "Multiple Dining Options", "Business Center", "Concierge Service", "Valet Parking"],
        sightSeeing: ["India Gate", "Red Fort", "Qutub Minar", "Lotus Temple", "Humayun's Tomb", "Akshardham Temple"],
        startingPrice: 18500,
        images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    },
    {
        email: "oberoi.udaivilas@example.com",
        password: "partner123",
        companyName: "The Oberoi Udaivilas",
        destinations: ["Udaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Ultra-Luxury", "Honeymoon", "Royal"],
        budgetRange: { min: 35000, max: 120000 },
        rating: 5,
        description: "Situated on the banks of Lake Pichola, The Oberoi Udaivilas is a magnificent palace hotel that epitomizes royal Rajasthani hospitality. With intricate architecture, private pools, and breathtaking lake views, it's a dream destination.",
        amenities: ["Private Pool Villas", "Spa", "Lake View Dining", "Boat Rides", "Cultural Performances", "Butler Service"],
        sightSeeing: ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon Ki Bari", "Bagore Ki Haveli", "Monsoon Palace"],
        startingPrice: 42000,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
    },
    {
        email: "taj.mahal.palace.mumbai@example.com",
        password: "partner123",
        companyName: "Taj Mahal Palace Mumbai",
        destinations: ["Mumbai", "Maharashtra"],
        type: "Hotel",
        specializations: ["Iconic", "Luxury", "Heritage"],
        budgetRange: { min: 25000, max: 85000 },
        rating: 5,
        description: "India's most iconic hotel, the Taj Mahal Palace Mumbai stands majestically overlooking the Arabian Sea and the Gateway of India. A symbol of Indian hospitality since 1903, it combines old-world charm with modern luxury.",
        amenities: ["Sea-facing Rooms", "Jiva Spa", "Zodiac Grill", "Heritage Wing", "Pool", "Shopping Arcade"],
        sightSeeing: ["Gateway of India", "Marine Drive", "Elephanta Caves", "Chhatrapati Shivaji Terminus", "Haji Ali Dargah", "Colaba Causeway"],
        startingPrice: 28500,
        images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800"],
    },
    {
        email: "leela.palace.bangalore@example.com",
        password: "partner123",
        companyName: "The Leela Palace Bangalore",
        destinations: ["Bangalore", "Karnataka"],
        type: "Hotel",
        specializations: ["Luxury", "Art", "Wellness"],
        budgetRange: { min: 12000, max: 45000 },
        rating: 5,
        description: "Inspired by the royal Mysore Palace, The Leela Palace Bangalore is an architectural marvel featuring hand-carved furniture, original artworks, and lush gardens. A sanctuary of luxury in India's Silicon Valley.",
        amenities: ["Art Gallery", "Spa", "Rooftop Pool", "Fine Dining", "Library", "Yoga Pavilion"],
        sightSeeing: ["Lalbagh Botanical Garden", "Bangalore Palace", "Cubbon Park", "Vidhana Soudha", "ISKCON Temple", "Tipu Sultan's Palace"],
        startingPrice: 14500,
        images: ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
    },
    {
        email: "wildflower.hall.shimla@example.com",
        password: "partner123",
        companyName: "Wildflower Hall Shimla",
        destinations: ["Shimla", "Himachal Pradesh"],
        type: "Hotel",
        specializations: ["Mountain", "Luxury", "Adventure"],
        budgetRange: { min: 18000, max: 55000 },
        rating: 5,
        description: "Perched at 8,250 feet in the Himalayas, Wildflower Hall offers panoramic views of snow-capped peaks and cedar forests. Once the residence of Lord Kitchener, it's now an Oberoi luxury retreat perfect for mountain lovers.",
        amenities: ["Mountain Views", "Spa", "Heated Pool", "Adventure Activities", "Fine Dining", "Bonfire Evenings"],
        sightSeeing: ["The Ridge", "Mall Road", "Jakhu Temple", "Christ Church", "Kufri", "Chadwick Falls"],
        startingPrice: 22000,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
    },
    {
        email: "rambagh.palace.jaipur@example.com",
        password: "partner123",
        companyName: "Rambagh Palace Jaipur",
        destinations: ["Jaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Royal", "Heritage", "Luxury"],
        budgetRange: { min: 30000, max: 150000 },
        rating: 5,
        description: "The former residence of the Maharaja of Jaipur, Rambagh Palace is a jewel of Rajasthan. With 47 acres of Mughal gardens, opulent suites, and royal dining experiences, it offers an authentic taste of royalty.",
        amenities: ["Palace Suites", "Spa", "Royal Gardens", "Heritage Tours", "Traditional Dining", "Vintage Car Rides"],
        sightSeeing: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Nahargarh Fort", "Jal Mahal"],
        startingPrice: 35000,
        images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"],
    },
    {
        email: "taj.exotica.goa@example.com",
        password: "partner123",
        companyName: "Taj Exotica Resort & Spa Goa",
        destinations: ["Goa"],
        type: "Hotel",
        specializations: ["Beach", "Luxury", "Wellness"],
        budgetRange: { min: 15000, max: 60000 },
        rating: 4,
        description: "Set amidst 56 acres of lush gardens and overlooking the Arabian Sea, Taj Exotica Goa is a Mediterranean-style resort offering pristine beaches, world-class spa treatments, and vibrant Goan culture.",
        amenities: ["Private Beach", "Jiva Spa", "9-hole Golf Course", "Water Sports", "Multiple Pools", "Kids Club"],
        sightSeeing: ["Basilica of Bom Jesus", "Fort Aguada", "Dudhsagar Falls", "Anjuna Beach", "Chapora Fort", "Spice Plantations"],
        startingPrice: 18000,
        images: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800"],
    },
    {
        email: "aman.i.khas.ranthambore@example.com",
        password: "partner123",
        companyName: "Aman-i-Khás Ranthambore",
        destinations: ["Ranthambore", "Rajasthan"],
        type: "Hotel",
        specializations: ["Wildlife", "Luxury", "Adventure"],
        budgetRange: { min: 80000, max: 250000 },
        rating: 5,
        description: "A luxurious tented camp on the outskirts of Ranthambore National Park, Aman-i-Khás offers an intimate wildlife experience. Combining adventure with Aman's signature luxury, it's perfect for tiger safaris and nature lovers.",
        amenities: ["Luxury Tents", "Private Dining", "Spa Tent", "Tiger Safaris", "Nature Walks", "Stargazing"],
        sightSeeing: ["Ranthambore Fort", "Tiger Safari", "Padam Talao", "Surwal Lake", "Trinetra Ganesh Temple", "Kachida Valley"],
        startingPrice: 95000,
        images: ["https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800"],
    },
    {
        email: "itc.grand.chola.chennai@example.com",
        password: "partner123",
        companyName: "ITC Grand Chola Chennai",
        destinations: ["Chennai", "Tamil Nadu"],
        type: "Hotel",
        specializations: ["Luxury", "Business", "Culture"],
        budgetRange: { min: 10000, max: 40000 },
        rating: 5,
        description: "Inspired by the grandeur of the Chola dynasty, ITC Grand Chola is South India's largest luxury hotel. With stunning architecture, multiple award-winning restaurants, and a world-class spa, it's a cultural landmark.",
        amenities: ["Kaya Kalp Spa", "Multiple Restaurants", "Grand Ballroom", "Pool", "Fitness Center", "Art Gallery"],
        sightSeeing: ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "Mahabalipuram", "San Thome Cathedral", "DakshinaChitra"],
        startingPrice: 12500,
        images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"],
    },
    {
        email: "vivanta.dal.view.srinagar@example.com",
        password: "partner123",
        companyName: "Vivanta Dal View Srinagar",
        destinations: ["Srinagar", "Kashmir"],
        type: "Hotel",
        specializations: ["Scenic", "Luxury", "Honeymoon"],
        budgetRange: { min: 15000, max: 50000 },
        rating: 4,
        description: "Overlooking the serene Dal Lake with the Zabarwan mountains as backdrop, Vivanta Dal View offers a perfect blend of Kashmiri hospitality and modern luxury. Experience shikara rides, Mughal gardens, and stunning sunsets.",
        amenities: ["Lake View Rooms", "Spa", "Kashmiri Cuisine", "Shikara Rides", "Garden", "Bonfire"],
        sightSeeing: ["Dal Lake", "Mughal Gardens", "Shankaracharya Temple", "Hazratbal Shrine", "Pari Mahal", "Nigeen Lake"],
        startingPrice: 18000,
        images: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800"],
    },
    {
        email: "taj.falaknuma.hyderabad@example.com",
        password: "partner123",
        companyName: "Taj Falaknuma Palace Hyderabad",
        destinations: ["Hyderabad", "Telangana"],
        type: "Hotel",
        specializations: ["Royal", "Heritage", "Luxury"],
        budgetRange: { min: 35000, max: 150000 },
        rating: 5,
        description: "Perched 2,000 feet above Hyderabad, Falaknuma Palace means 'Mirror of the Sky'. This opulent Nizam's palace features Venetian chandeliers, rare manuscripts, and the world's longest dining table. A truly regal experience.",
        amenities: ["Palace Suites", "Jiva Spa", "Vintage Car Tours", "Royal Dining", "Billiards Room", "Library"],
        sightSeeing: ["Charminar", "Golconda Fort", "Ramoji Film City", "Hussain Sagar Lake", "Salar Jung Museum", "Chowmahalla Palace"],
        startingPrice: 45000,
        images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    },
    {
        email: "kumarakom.lake.resort@example.com",
        password: "partner123",
        companyName: "Kumarakom Lake Resort",
        destinations: ["Kumarakom", "Kerala"],
        type: "Hotel",
        specializations: ["Backwaters", "Ayurveda", "Luxury"],
        budgetRange: { min: 12000, max: 45000 },
        rating: 4,
        description: "Set on the banks of Vembanad Lake, Kumarakom Lake Resort offers traditional Kerala architecture, Ayurvedic treatments, and houseboat experiences. Immerse yourself in the tranquil backwaters of God's Own Country.",
        amenities: ["Heritage Villas", "Ayurveda Spa", "Houseboat Cruises", "Infinity Pool", "Traditional Cuisine", "Bird Sanctuary Tours"],
        sightSeeing: ["Vembanad Lake", "Kumarakom Bird Sanctuary", "Pathiramanal Island", "Bay Island Driftwood Museum", "Aruvikkuzhi Waterfall", "Vaikom Mahadeva Temple"],
        startingPrice: 15000,
        images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800"],
    },
    {
        email: "wildernest.goa@example.com",
        password: "partner123",
        companyName: "Wildernest Nature Resort",
        destinations: ["Goa"],
        type: "Hotel",
        specializations: ["Nature", "Eco-Tourism", "Adventure"],
        budgetRange: { min: 8000, max: 25000 },
        rating: 4,
        description: "Nestled in the Western Ghats on the Goa-Karnataka border, Wildernest is an eco-resort offering jungle treks, bird watching, and waterfall rappelling. Perfect for nature enthusiasts seeking adventure and tranquility.",
        amenities: ["Jungle Cottages", "Nature Trails", "Bird Watching", "Waterfall Rappelling", "Organic Food", "Campfire"],
        sightSeeing: ["Dudhsagar Falls", "Mollem National Park", "Tambdi Surla Temple", "Bhagwan Mahavir Sanctuary", "Devil's Canyon", "Netravali Wildlife Sanctuary"],
        startingPrice: 9500,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
    },
    {
        email: "evolve.back.coorg@example.com",
        password: "partner123",
        companyName: "Evolve Back Coorg",
        destinations: ["Coorg", "Karnataka"],
        type: "Hotel",
        specializations: ["Plantation", "Luxury", "Wellness"],
        budgetRange: { min: 20000, max: 65000 },
        rating: 5,
        description: "Set amidst 300 acres of coffee and spice plantations, Evolve Back Coorg offers luxury villas with private pools, plantation tours, and authentic Coorgi cuisine. Experience the misty hills and rich culture of Coorg.",
        amenities: ["Private Pool Villas", "Spa", "Plantation Tours", "Infinity Pool", "Coorgi Cuisine", "Nature Walks"],
        sightSeeing: ["Abbey Falls", "Raja's Seat", "Dubare Elephant Camp", "Talacauvery", "Namdroling Monastery", "Iruppu Falls"],
        startingPrice: 24000,
        images: ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
    },
    {
        email: "ananda.himalayas@example.com",
        password: "partner123",
        companyName: "Ananda in the Himalayas",
        destinations: ["Rishikesh", "Uttarakhand"],
        type: "Hotel",
        specializations: ["Wellness", "Spa", "Yoga"],
        budgetRange: { min: 30000, max: 100000 },
        rating: 5,
        description: "A destination spa resort in the Himalayan foothills, Ananda combines traditional Ayurveda, Yoga, and Vedanta with international wellness experiences. Set in a 100-acre Maharaja's palace estate overlooking the Ganges.",
        amenities: ["Spa Pavilion", "Yoga Pavilion", "Ayurveda", "Meditation", "Organic Cuisine", "Palace Suites"],
        sightSeeing: ["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Beatles Ashram", "Neelkanth Mahadev Temple", "Rajaji National Park"],
        startingPrice: 35000,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
    },
    {
        email: "suryagarh.jaisalmer@example.com",
        password: "partner123",
        companyName: "Suryagarh Jaisalmer",
        destinations: ["Jaisalmer", "Rajasthan"],
        type: "Hotel",
        specializations: ["Desert", "Heritage", "Luxury"],
        budgetRange: { min: 18000, max: 60000 },
        rating: 5,
        description: "A magnificent fort-palace in the Thar Desert, Suryagarh offers an authentic Rajasthani experience with camel safaris, dune dinners, and cultural performances. Experience the golden city's magic in ultimate luxury.",
        amenities: ["Desert Safaris", "Spa", "Dune Dining", "Cultural Shows", "Heritage Tours", "Pool"],
        sightSeeing: ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli", "Gadisar Lake", "Bada Bagh", "Kuldhara Village"],
        startingPrice: 22000,
        images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"],
    },
    {
        email: "taj.lake.palace.udaipur@example.com",
        password: "partner123",
        companyName: "Taj Lake Palace Udaipur",
        destinations: ["Udaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Iconic", "Luxury", "Romantic"],
        budgetRange: { min: 40000, max: 150000 },
        rating: 5,
        description: "Floating like a white marble vision on Lake Pichola, the Taj Lake Palace is one of the world's most romantic hotels. Featured in James Bond's Octopussy, it offers unparalleled luxury and breathtaking views.",
        amenities: ["Lake Palace Suites", "Jiva Spa", "Boat Transfers", "Rooftop Dining", "Lily Pond Courtyard", "Butler Service"],
        sightSeeing: ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon Ki Bari", "Fateh Sagar Lake", "Sajjangarh Palace"],
        startingPrice: 48000,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
    },
    {
        email: "alila.fort.bishangarh@example.com",
        password: "partner123",
        companyName: "Alila Fort Bishangarh",
        destinations: ["Jaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Heritage", "Luxury", "Unique"],
        budgetRange: { min: 18000, max: 65000 },
        rating: 5,
        description: "A 230-year-old warrior fort transformed into a luxury hotel, Alila Fort Bishangarh rises dramatically from a granite hill. With contemporary design respecting heritage architecture, it offers a unique blend of old and new.",
        amenities: ["Fort Suites", "Spa", "Rooftop Dining", "Heritage Walks", "Infinity Pool", "Yoga Pavilion"],
        sightSeeing: ["Amber Fort", "Jaipur City Palace", "Hawa Mahal", "Nahargarh Fort", "Jal Mahal", "Chand Baori"],
        startingPrice: 21000,
        images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"],
    },
    {
        email: "devi.garh.udaipur@example.com",
        password: "partner123",
        companyName: "Devi Garh by Lebua",
        destinations: ["Udaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Boutique", "Luxury", "Design"],
        budgetRange: { min: 20000, max: 75000 },
        rating: 5,
        description: "An 18th-century palace transformed into a contemporary luxury hotel, Devi Garh features minimalist design with traditional elements. Set in the Aravalli Hills, it offers stunning views and a world-class spa.",
        amenities: ["Palace Suites", "Spa", "Infinity Pool", "Organic Farm", "Yoga", "Heritage Tours"],
        sightSeeing: ["Eklingji Temple", "Nagda Temples", "Delwara", "Nathdwara", "Kumbhalgarh Fort", "Ranakpur Jain Temple"],
        startingPrice: 24000,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
    },
    {
        email: "orange.county.coorg@example.com",
        password: "partner123",
        companyName: "Orange County Coorg",
        destinations: ["Coorg", "Karnataka"],
        type: "Hotel",
        specializations: ["Plantation", "Eco-Luxury", "Wellness"],
        budgetRange: { min: 18000, max: 60000 },
        rating: 4,
        description: "Nestled in a 300-acre coffee and spice plantation, Orange County Coorg offers colonial-style cottages, plantation walks, and authentic Coorgi experiences. A perfect retreat for nature lovers and coffee enthusiasts.",
        amenities: ["Plantation Cottages", "Spa", "Coffee Tours", "Bird Watching", "Coorgi Cuisine", "Nature Trails"],
        sightSeeing: ["Abbey Falls", "Raja's Seat", "Madikeri Fort", "Omkareshwara Temple", "Dubare Elephant Camp", "Talacauvery"],
        startingPrice: 21000,
        images: ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
    },
];

const seedIndianPartners = async () => {
    try {
        // Clear existing Indian partners
        await PartnerProfile.deleteMany({ destinations: { $in: ["Delhi", "Udaipur", "Mumbai", "Bangalore", "Shimla", "Jaipur", "Goa", "Ranthambore", "Chennai", "Srinagar", "Hyderabad", "Kumarakom", "Coorg", "Rishikesh", "Jaisalmer"] } });
        console.log('Cleared existing Indian partners');

        for (const partnerData of indianPartners) {
            const { email, password, ...profileData } = partnerData;

            // Create User
            const hashedPassword = await bcrypt.hash(password, 10);
            let user = await User.findOne({ email });

            if (!user) {
                user = await User.create({
                    name: profileData.companyName,
                    email,
                    password: hashedPassword,
                    role: 'PARTNER',
                });
            }

            // Create Partner Profile
            await PartnerProfile.create({
                userId: user._id,
                ...profileData,
            });
        }

        console.log(`Seeded ${indianPartners.length} Indian Partners Successfully`);
        process.exit(0);
    } catch (error) {
        console.error('Error seeding Indian partners:', error);
        process.exit(1);
    }
};

seedIndianPartners();
