export const indianPartners = [
    {
        email: "taj.palace.delhi@example.com",
        password: "partner123",
        companyName: "The Taj Palace Delhi",
        destinations: ["Delhi", "New Delhi"],
        type: "Hotel",
        specializations: ["Luxury", "Heritage", "Business"],
        budgetRange: { min: 15000, max: 45000 },
        rating: 5,
        description: "An iconic luxury hotel in the heart of India's capital, The Taj Palace Delhi offers world-class hospitality with stunning views of the city. Experience regal comfort with modern amenities, Michelin-starred dining, and impeccable service.",
        amenities: ["Rooftop Pool", "Jiva Spa", "Multiple Dining Options", "Business Center", "Concierge Service", "Valet Parking"],
        sightSeeing: ["India Gate", "Red Fort", "Qutub Minar", "Lotus Temple", "Humayun's Tomb", "Akshardham Temple"],
        startingPrice: 18500,
        images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    },
    {
        email: "oberoi.udaivilas@example.com",
        password: "partner123",
        companyName: "The Oberoi Udaivilas",
        destinations: ["Udaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Ultra-Luxury", "Honeymoon", "Royal"],
        budgetRange: { min: 35000, max: 120000 },
        rating: 5,
        description: "Situated on the banks of Lake Pichola, The Oberoi Udaivilas is a magnificent palace hotel that epitomizes royal Rajasthani hospitality. With intricate architecture, private pools, and breathtaking lake views, it's a dream destination.",
        amenities: ["Private Pool Villas", "Spa", "Lake View Dining", "Boat Rides", "Cultural Performances", "Butler Service"],
        sightSeeing: ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon Ki Bari", "Bagore Ki Haveli", "Monsoon Palace"],
        startingPrice: 42000,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
    },
    {
        email: "taj.mahal.palace.mumbai@example.com",
        password: "partner123",
        companyName: "Taj Mahal Palace Mumbai",
        destinations: ["Mumbai", "Maharashtra"],
        type: "Hotel",
        specializations: ["Iconic", "Luxury", "Heritage"],
        budgetRange: { min: 25000, max: 85000 },
        rating: 5,
        description: "India's most iconic hotel, the Taj Mahal Palace Mumbai stands majestically overlooking the Arabian Sea and the Gateway of India. A symbol of Indian hospitality since 1903, it combines old-world charm with modern luxury.",
        amenities: ["Sea-facing Rooms", "Jiva Spa", "Zodiac Grill", "Heritage Wing", "Pool", "Shopping Arcade"],
        sightSeeing: ["Gateway of India", "Marine Drive", "Elephanta Caves", "Chhatrapati Shivaji Terminus", "Haji Ali Dargah", "Colaba Causeway"],
        startingPrice: 28500,
        images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800"],
    },
    {
        email: "leela.palace.bangalore@example.com",
        password: "partner123",
        companyName: "The Leela Palace Bangalore",
        destinations: ["Bangalore", "Karnataka"],
        type: "Hotel",
        specializations: ["Luxury", "Art", "Wellness"],
        budgetRange: { min: 12000, max: 45000 },
        rating: 5,
        description: "Inspired by the royal Mysore Palace, The Leela Palace Bangalore is an architectural marvel featuring hand-carved furniture, original artworks, and lush gardens. A sanctuary of luxury in India's Silicon Valley.",
        amenities: ["Art Gallery", "Spa", "Rooftop Pool", "Fine Dining", "Library", "Yoga Pavilion"],
        sightSeeing: ["Lalbagh Botanical Garden", "Bangalore Palace", "Cubbon Park", "Vidhana Soudha", "ISKCON Temple", "Tipu Sultan's Palace"],
        startingPrice: 14500,
        images: ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
    },
    {
        email: "wildflower.hall.shimla@example.com",
        password: "partner123",
        companyName: "Wildflower Hall Shimla",
        destinations: ["Shimla", "Himachal Pradesh"],
        type: "Hotel",
        specializations: ["Mountain", "Luxury", "Adventure"],
        budgetRange: { min: 18000, max: 55000 },
        rating: 5,
        description: "Perched at 8,250 feet in the Himalayas, Wildflower Hall offers panoramic views of snow-capped peaks and cedar forests. Once the residence of Lord Kitchener, it's now an Oberoi luxury retreat perfect for mountain lovers.",
        amenities: ["Mountain Views", "Spa", "Heated Pool", "Adventure Activities", "Fine Dining", "Bonfire Evenings"],
        sightSeeing: ["The Ridge", "Mall Road", "Jakhu Temple", "Christ Church", "Kufri", "Chadwick Falls"],
        startingPrice: 22000,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
    },
    {
        email: "rambagh.palace.jaipur@example.com",
        password: "partner123",
        companyName: "Rambagh Palace Jaipur",
        destinations: ["Jaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Royal", "Heritage", "Luxury"],
        budgetRange: { min: 30000, max: 150000 },
        rating: 5,
        description: "The former residence of the Maharaja of Jaipur, Rambagh Palace is a jewel of Rajasthan. With 47 acres of Mughal gardens, opulent suites, and royal dining experiences, it offers an authentic taste of royalty.",
        amenities: ["Palace Suites", "Spa", "Royal Gardens", "Heritage Tours", "Traditional Dining", "Vintage Car Rides"],
        sightSeeing: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Nahargarh Fort", "Jal Mahal"],
        startingPrice: 35000,
        images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"],
    },
    {
        email: "taj.exotica.goa@example.com",
        password: "partner123",
        companyName: "Taj Exotica Resort & Spa Goa",
        destinations: ["Goa"],
        type: "Hotel",
        specializations: ["Beach", "Luxury", "Wellness"],
        budgetRange: { min: 15000, max: 60000 },
        rating: 4,
        description: "Set amidst 56 acres of lush gardens and overlooking the Arabian Sea, Taj Exotica Goa is a Mediterranean-style resort offering pristine beaches, world-class spa treatments, and vibrant Goan culture.",
        amenities: ["Private Beach", "Jiva Spa", "9-hole Golf Course", "Water Sports", "Multiple Pools", "Kids Club"],
        sightSeeing: ["Basilica of Bom Jesus", "Fort Aguada", "Dudhsagar Falls", "Anjuna Beach", "Chapora Fort", "Spice Plantations"],
        startingPrice: 18000,
        images: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800"],
    },
    {
        email: "aman.i.khas.ranthambore@example.com",
        password: "partner123",
        companyName: "Aman-i-Khás Ranthambore",
        destinations: ["Ranthambore", "Rajasthan"],
        type: "Hotel",
        specializations: ["Wildlife", "Luxury", "Adventure"],
        budgetRange: { min: 80000, max: 250000 },
        rating: 5,
        description: "A luxurious tented camp on the outskirts of Ranthambore National Park, Aman-i-Khás offers an intimate wildlife experience. Combining adventure with Aman's signature luxury, it's perfect for tiger safaris and nature lovers.",
        amenities: ["Luxury Tents", "Private Dining", "Spa Tent", "Tiger Safaris", "Nature Walks", "Stargazing"],
        sightSeeing: ["Ranthambore Fort", "Tiger Safari", "Padam Talao", "Surwal Lake", "Trinetra Ganesh Temple", "Kachida Valley"],
        startingPrice: 95000,
        images: ["https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800"],
    },
    {
        email: "itc.grand.chola.chennai@example.com",
        password: "partner123",
        companyName: "ITC Grand Chola Chennai",
        destinations: ["Chennai", "Tamil Nadu"],
        type: "Hotel",
        specializations: ["Luxury", "Business", "Culture"],
        budgetRange: { min: 10000, max: 40000 },
        rating: 5,
        description: "Inspired by the grandeur of the Chola dynasty, ITC Grand Chola is South India's largest luxury hotel. With stunning architecture, multiple award-winning restaurants, and a world-class spa, it's a cultural landmark.",
        amenities: ["Kaya Kalp Spa", "Multiple Restaurants", "Grand Ballroom", "Pool", "Fitness Center", "Art Gallery"],
        sightSeeing: ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "Mahabalipuram", "San Thome Cathedral", "DakshinaChitra"],
        startingPrice: 12500,
        images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"],
    },
    {
        email: "vivanta.dal.view.srinagar@example.com",
        password: "partner123",
        companyName: "Vivanta Dal View Srinagar",
        destinations: ["Srinagar", "Kashmir"],
        type: "Hotel",
        specializations: ["Scenic", "Luxury", "Honeymoon"],
        budgetRange: { min: 15000, max: 50000 },
        rating: 4,
        description: "Overlooking the serene Dal Lake with the Zabarwan mountains as backdrop, Vivanta Dal View offers a perfect blend of Kashmiri hospitality and modern luxury. Experience shikara rides, Mughal gardens, and stunning sunsets.",
        amenities: ["Lake View Rooms", "Spa", "Kashmiri Cuisine", "Shikara Rides", "Garden", "Bonfire"],
        sightSeeing: ["Dal Lake", "Mughal Gardens", "Shankaracharya Temple", "Hazratbal Shrine", "Pari Mahal", "Nigeen Lake"],
        startingPrice: 18000,
        images: ["https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800"],
    },
    {
        email: "taj.falaknuma.hyderabad@example.com",
        password: "partner123",
        companyName: "Taj Falaknuma Palace Hyderabad",
        destinations: ["Hyderabad", "Telangana"],
        type: "Hotel",
        specializations: ["Royal", "Heritage", "Luxury"],
        budgetRange: { min: 35000, max: 150000 },
        rating: 5,
        description: "Perched 2,000 feet above Hyderabad, Falaknuma Palace means 'Mirror of the Sky'. This opulent Nizam's palace features Venetian chandeliers, rare manuscripts, and the world's longest dining table. A truly regal experience.",
        amenities: ["Palace Suites", "Jiva Spa", "Vintage Car Tours", "Royal Dining", "Billiards Room", "Library"],
        sightSeeing: ["Charminar", "Golconda Fort", "Ramoji Film City", "Hussain Sagar Lake", "Salar Jung Museum", "Chowmahalla Palace"],
        startingPrice: 45000,
        images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    },
    {
        email: "kumarakom.lake.resort@example.com",
        password: "partner123",
        companyName: "Kumarakom Lake Resort",
        destinations: ["Kumarakom", "Kerala"],
        type: "Hotel",
        specializations: ["Backwaters", "Ayurveda", "Luxury"],
        budgetRange: { min: 12000, max: 45000 },
        rating: 4,
        description: "Set on the banks of Vembanad Lake, Kumarakom Lake Resort offers traditional Kerala architecture, Ayurvedic treatments, and houseboat experiences. Immerse yourself in the tranquil backwaters of God's Own Country.",
        amenities: ["Heritage Villas", "Ayurveda Spa", "Houseboat Cruises", "Infinity Pool", "Traditional Cuisine", "Bird Sanctuary Tours"],
        sightSeeing: ["Vembanad Lake", "Kumarakom Bird Sanctuary", "Pathiramanal Island", "Bay Island Driftwood Museum", "Aruvikkuzhi Waterfall", "Vaikom Mahadeva Temple"],
        startingPrice: 15000,
        images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800"],
    },
    {
        email: "wildernest.goa@example.com",
        password: "partner123",
        companyName: "Wildernest Nature Resort",
        destinations: ["Goa"],
        type: "Hotel",
        specializations: ["Nature", "Eco-Tourism", "Adventure"],
        budgetRange: { min: 8000, max: 25000 },
        rating: 4,
        description: "Nestled in the Western Ghats on the Goa-Karnataka border, Wildernest is an eco-resort offering jungle treks, bird watching, and waterfall rappelling. Perfect for nature enthusiasts seeking adventure and tranquility.",
        amenities: ["Jungle Cottages", "Nature Trails", "Bird Watching", "Waterfall Rappelling", "Organic Food", "Campfire"],
        sightSeeing: ["Dudhsagar Falls", "Mollem National Park", "Tambdi Surla Temple", "Bhagwan Mahavir Sanctuary", "Devil's Canyon", "Netravali Wildlife Sanctuary"],
        startingPrice: 9500,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
    },
    {
        email: "evolve.back.coorg@example.com",
        password: "partner123",
        companyName: "Evolve Back Coorg",
        destinations: ["Coorg", "Karnataka"],
        type: "Hotel",
        specializations: ["Plantation", "Luxury", "Wellness"],
        budgetRange: { min: 20000, max: 65000 },
        rating: 5,
        description: "Set amidst 300 acres of coffee and spice plantations, Evolve Back Coorg offers luxury villas with private pools, plantation tours, and authentic Coorgi cuisine. Experience the misty hills and rich culture of Coorg.",
        amenities: ["Private Pool Villas", "Spa", "Plantation Tours", "Infinity Pool", "Coorgi Cuisine", "Nature Walks"],
        sightSeeing: ["Abbey Falls", "Raja's Seat", "Dubare Elephant Camp", "Talacauvery", "Namdroling Monastery", "Iruppu Falls"],
        startingPrice: 24000,
        images: ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
    },
    {
        email: "ananda.himalayas@example.com",
        password: "partner123",
        companyName: "Ananda in the Himalayas",
        destinations: ["Rishikesh", "Uttarakhand"],
        type: "Hotel",
        specializations: ["Wellness", "Spa", "Yoga"],
        budgetRange: { min: 30000, max: 100000 },
        rating: 5,
        description: "A destination spa resort in the Himalayan foothills, Ananda combines traditional Ayurveda, Yoga, and Vedanta with international wellness experiences. Set in a 100-acre Maharaja's palace estate overlooking the Ganges.",
        amenities: ["Spa Pavilion", "Yoga Pavilion", "Ayurveda", "Meditation", "Organic Cuisine", "Palace Suites"],
        sightSeeing: ["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Beatles Ashram", "Neelkanth Mahadev Temple", "Rajaji National Park"],
        startingPrice: 35000,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
    },
    {
        email: "suryagarh.jaisalmer@example.com",
        password: "partner123",
        companyName: "Suryagarh Jaisalmer",
        destinations: ["Jaisalmer", "Rajasthan"],
        type: "Hotel",
        specializations: ["Desert", "Heritage", "Luxury"],
        budgetRange: { min: 18000, max: 60000 },
        rating: 5,
        description: "A magnificent fort-palace in the Thar Desert, Suryagarh offers an authentic Rajasthani experience with camel safaris, dune dinners, and cultural performances. Experience the golden city's magic in ultimate luxury.",
        amenities: ["Desert Safaris", "Spa", "Dune Dining", "Cultural Shows", "Heritage Tours", "Pool"],
        sightSeeing: ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli", "Gadisar Lake", "Bada Bagh", "Kuldhara Village"],
        startingPrice: 22000,
        images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"],
    },
    {
        email: "taj.lake.palace.udaipur@example.com",
        password: "partner123",
        companyName: "Taj Lake Palace Udaipur",
        destinations: ["Udaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Iconic", "Luxury", "Romantic"],
        budgetRange: { min: 40000, max: 150000 },
        rating: 5,
        description: "Floating like a white marble vision on Lake Pichola, the Taj Lake Palace is one of the world's most romantic hotels. Featured in James Bond's Octopussy, it offers unparalleled luxury and breathtaking views.",
        amenities: ["Lake Palace Suites", "Jiva Spa", "Boat Transfers", "Rooftop Dining", "Lily Pond Courtyard", "Butler Service"],
        sightSeeing: ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon Ki Bari", "Fateh Sagar Lake", "Sajjangarh Palace"],
        startingPrice: 48000,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
    },
    {
        email: "alila.fort.bishangarh@example.com",
        password: "partner123",
        companyName: "Alila Fort Bishangarh",
        destinations: ["Jaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Heritage", "Luxury", "Unique"],
        budgetRange: { min: 18000, max: 65000 },
        rating: 5,
        description: "A 230-year-old warrior fort transformed into a luxury hotel, Alila Fort Bishangarh rises dramatically from a granite hill. With contemporary design respecting heritage architecture, it offers a unique blend of old and new.",
        amenities: ["Fort Suites", "Spa", "Rooftop Dining", "Heritage Walks", "Infinity Pool", "Yoga Pavilion"],
        sightSeeing: ["Amber Fort", "Jaipur City Palace", "Hawa Mahal", "Nahargarh Fort", "Jal Mahal", "Chand Baori"],
        startingPrice: 21000,
        images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"],
    },
    {
        email: "devi.garh.udaipur@example.com",
        password: "partner123",
        companyName: "Devi Garh by Lebua",
        destinations: ["Udaipur", "Rajasthan"],
        type: "Hotel",
        specializations: ["Boutique", "Luxury", "Design"],
        budgetRange: { min: 20000, max: 75000 },
        rating: 5,
        description: "An 18th-century palace transformed into a contemporary luxury hotel, Devi Garh features minimalist design with traditional elements. Set in the Aravalli Hills, it offers stunning views and a world-class spa.",
        amenities: ["Palace Suites", "Spa", "Infinity Pool", "Organic Farm", "Yoga", "Heritage Tours"],
        sightSeeing: ["Eklingji Temple", "Nagda Temples", "Delwara", "Nathdwara", "Kumbhalgarh Fort", "Ranakpur Jain Temple"],
        startingPrice: 24000,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
    },
    {
        email: "orange.county.coorg@example.com",
        password: "partner123",
        companyName: "Orange County Coorg",
        destinations: ["Coorg", "Karnataka"],
        type: "Hotel",
        specializations: ["Plantation", "Eco-Luxury", "Wellness"],
        budgetRange: { min: 18000, max: 60000 },
        rating: 4,
        description: "Nestled in a 300-acre coffee and spice plantation, Orange County Coorg offers colonial-style cottages, plantation walks, and authentic Coorgi experiences. A perfect retreat for nature lovers and coffee enthusiasts.",
        amenities: ["Plantation Cottages", "Spa", "Coffee Tours", "Bird Watching", "Coorgi Cuisine", "Nature Trails"],
        sightSeeing: ["Abbey Falls", "Raja's Seat", "Madikeri Fort", "Omkareshwara Temple", "Dubare Elephant Camp", "Talacauvery"],
        startingPrice: 21000,
        images: ["https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800"],
    },
];

export const internationalPartners = [
    // Maldives
    {
        companyName: "Soneva Jani",
        destinations: ["Maldives"],
        type: "Hotel",
        specializations: ["Luxury", "Honeymoon", "Wellness"],
        budgetRange: { min: 150000, max: 1000000 },
        rating: 5,
        description: "A benchmark for overwater luxury, Soneva Jani offers a collection of Water Villas and Island Reserves set within a lagoon of crystal clear waters. Each villa comes with its own private pool and a retractable roof to stargaze from the master bedroom.",
        amenities: ["Private Pool", "Retractable Roof", "Water Slide", "Cinema Paradiso", "Observatory", "Organic Gardens"],
        sightSeeing: ["Noonu Atoll Marine Park", "Dolphin Cruise", "Private Sandbank"],
        startingPrice: 250000,
        images: [
            "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Gili Lankanfushi",
        destinations: ["Maldives"],
        type: "Hotel",
        specializations: ["Eco-Luxury", "Honeymoon"],
        budgetRange: { min: 100000, max: 500000 },
        rating: 5,
        description: "Gili Lankanfushi is an intimate coral island in a sparkling lagoon, with jetties threading across the water out to spacious villa accommodations. It is a place of positive energy and absolute privacy.",
        amenities: ["Overwater Bar", "Meera Spa", "Jungle Cinema", "Underground Wine Cellar", "Mr. Friday Butler Service"],
        sightSeeing: ["Manta Ray Point", "Local Island Visit", "Sunset Dhoni Cruise"],
        startingPrice: 120000,
        images: [
            "https://images.unsplash.com/photo-1439066615861-d1fbced6530e?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Velaa Private Island",
        destinations: ["Maldives"],
        type: "Hotel",
        specializations: ["Ultra-Luxury", "Privacy"],
        budgetRange: { min: 300000, max: 1500000 },
        rating: 5,
        description: "Born from a dream to create a 'beyond luxury' exclusive boutique hideaway. Velaa Private Island is the realization of a dream to create a 'beyond luxury' exclusive boutique hideaway in the Maldives.",
        amenities: ["Golf Academy", "Snow Room", "Clarins Spa", "Private Submarine", "Kids Club"],
        sightSeeing: ["Turtle Conservation", "Private Yacht Charter", "Night Golf"],
        startingPrice: 350000,
        images: [
            "https://images.unsplash.com/photo-1590523741831-ab7f8512d568?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "One&Only Reethi Rah",
        destinations: ["Maldives"],
        type: "Hotel",
        specializations: ["Family", "Luxury"],
        budgetRange: { min: 200000, max: 800000 },
        rating: 4,
        description: "Surrounded by the wonders of the Indian Ocean, One&Only Reethi Rah makes its home on one of the largest islands in North Malé Atoll. A jewel among a string of coral atolls, lagoons and white sands.",
        amenities: ["12 Beaches", "KidsOnly Club", "ESPA", "Climbing Wall", "FIFA Certified Football Pitch"],
        sightSeeing: ["Shark Safari", "Big Game Fishing", "Island Picnic"],
        startingPrice: 220000,
        images: [
            "https://images.unsplash.com/photo-1512100356356-de1b84283e18?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1586611292717-f828b167408c?q=80&w=1000&auto=format&fit=crop"
        ]
    },

    // Paris
    {
        companyName: "Four Seasons Hotel George V",
        destinations: ["Paris", "France"],
        type: "Hotel",
        specializations: ["Luxury", "City", "Gastronomy"],
        budgetRange: { min: 150000, max: 600000 },
        rating: 5,
        description: "An art deco landmark built in 1928, Four Seasons Hotel George V is nestled in the Golden Triangle of Paris, just off the historic Champs-Elysées. It features three Michelin-starred restaurants.",
        amenities: ["Michelin Dining", "Decadent Spa", "Flower Arrangements", "Indoor Pool", "Concierge"],
        sightSeeing: ["Eiffel Tower", "Arc de Triomphe", "Champs-Elysées"],
        startingPrice: 180000,
        images: [
            "https://images.unsplash.com/photo-1560131914-6870372444d8?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1499856871940-a09627c6dcf6?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "The Ritz Paris",
        destinations: ["Paris", "France"],
        type: "Hotel",
        specializations: ["History", "Luxury"],
        budgetRange: { min: 200000, max: 700000 },
        rating: 5,
        description: "The Ritz Paris is a hotel in central Paris, overlooking the Place Vendôme in the city's 1st arrondissement. A member of the Leading Hotels of the World, it is known for its grand decor and famous guests.",
        amenities: ["Hemingway Bar", "Ritz Club Paris", "Cooking School", "Chanel Spa", "Private Garden"],
        sightSeeing: ["Place Vendôme", "Louvre Museum", "Opera Garnier"],
        startingPrice: 210000,
        images: [
            "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Le Meurice",
        destinations: ["Paris", "France"],
        type: "Hotel",
        specializations: ["Art", "Luxury"],
        budgetRange: { min: 120000, max: 500000 },
        rating: 4,
        description: "Ideally located opposite the Tuileries Garden, between Place de la Concorde and the Louvre Museum, Le Meurice has held sway as the jewel in the crown of French luxury hotels since 1835.",
        amenities: ["Valmont Spa", "Alain Ducasse Dining", "Pastry Shop", "Pet Friendly", "Fitness Center"],
        sightSeeing: ["Tuileries Garden", "Musée d'Orsay", "Rue de Rivoli"],
        startingPrice: 140000,
        images: [
            "https://images.unsplash.com/photo-1549651721-f9b050d4403f?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1550355291-bbee04a92027?q=80&w=1000&auto=format&fit=crop"
        ]
    },

    // Bali
    {
        companyName: "Viceroy Bali",
        destinations: ["Bali", "Indonesia"],
        type: "Hotel",
        specializations: ["Jungle", "Honeymoon", "Wellness"],
        budgetRange: { min: 40000, max: 200000 },
        rating: 5,
        description: "Family owned and operated, Viceroy Bali is a luxury resort with 40 private pool villas. It sits in the Valley of the Kings, a name given by locals for the generations of Balinese royalty who have resided in nearby villages.",
        amenities: ["Infinity Pool", "Lembah Spa", "Cascades Restaurant", "Helipad", "Yoga Pavilion"],
        sightSeeing: ["Ubud Monkey Forest", "Tegallalang Rice Terrace", "Goa Gajah"],
        startingPrice: 55000,
        images: [
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1573790387438-4da905039392?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Mandapa, a Ritz-Carlton Reserve",
        destinations: ["Bali", "Indonesia"],
        type: "Hotel",
        specializations: ["Culture", "Luxury", "Nature"],
        budgetRange: { min: 80000, max: 300000 },
        rating: 5,
        description: "Fronting the Ayung River near the Ubud jungle, Mandapa, a Ritz-Carlton Reserve offers individually tailored spiritual, wellness, and health programs as well as the finest dining.",
        amenities: ["Riverfront Dining", "Vitality Pool", "Organic Farm", "Kids Hut", "Butler Service"],
        sightSeeing: ["Campuhan Ridge Walk", "Tirta Empul Temple", "Bali Swing"],
        startingPrice: 90000,
        images: [
            "https://images.unsplash.com/photo-1552853843-bf7e211bb43f?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Amankila",
        destinations: ["Bali", "Indonesia"],
        type: "Hotel",
        specializations: ["Secluded", "Architecture"],
        budgetRange: { min: 70000, max: 250000 },
        rating: 4,
        description: "Claiming a breathtaking stretch of coastline on the Lombok Strait, Amankila rests on a lush hillside beneath the sacred Mount Agung. Connected by frangipani-lined walkways, stilted suites offer spectacular views.",
        amenities: ["Three-tier Pool", "Beach Club", "Library", "Massage Pavilions", "Water Sports"],
        sightSeeing: ["Tenganan Village", "Water Palaces", "Lempuyang Temple"],
        startingPrice: 85000,
        images: [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1000&auto=format&fit=crop"
        ]
    },

    {
        companyName: "Burj Al Arab Jumeirah",
        destinations: ["Dubai", "UAE"],
        type: "Hotel",
        specializations: ["Ultra-Luxury", "Iconic"],
        budgetRange: { min: 150000, max: 1000000 },
        rating: 5,
        description: "The distinctive sail-shaped silhouette of Burj Al Arab Jumeirah is more than just a stunning hotel, it is a symbol of modern Dubai. Repeatedly voted the world's most luxurious hotel.",
        amenities: ["Helipad", "Talise Spa", "Private Beach", "Aquarium Restaurant", "Rolls-Royce Fleet"],
        sightSeeing: ["Wild Wadi Waterpark", "Palm Jumeirah", "Dubai Mall"],
        startingPrice: 180000,
        images: [
            "https://images.unsplash.com/photo-1528702748617-c64d49f918af?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1512453979798-5ea9ba6a80f6?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Atlantis The Royal",
        destinations: ["Dubai", "UAE"],
        type: "Hotel",
        specializations: ["Entertainment", "Luxury"],
        budgetRange: { min: 60000, max: 400000 },
        rating: 5,
        description: "A new icon of Dubai, Atlantis The Royal welcomes you to an experience that will completely redefine your perspective of luxury. Crafted by the world’s leading designers, architects and artists.",
        amenities: ["Cloud 22 Skypool", "Nobu by the Beach", "Awaken Wellness", "Royal Club", "Fountains"],
        sightSeeing: ["Aquaventure Waterpark", "The Lost Chambers", "The Pointe"],
        startingPrice: 75000,
        images: [
            "https://images.unsplash.com/photo-1546412414-e1885259563a?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "One&Only The Palm",
        destinations: ["Dubai", "UAE"],
        type: "Hotel",
        specializations: ["Secluded", "Beach"],
        budgetRange: { min: 90000, max: 350000 },
        rating: 4,
        description: "Dubai's most intimate seaside enclave. Immerse yourself in the romance of the Riviera, on a private peninsula of the Palm Island. A tranquil haven for those seeking total relaxation.",
        amenities: ["Guerlain Spa", "Private Marina", "Temperature-controlled Pool", "Tennis Court", "Beachfront Villas"],
        sightSeeing: ["Dubai Marina", "Skydive Dubai", "Ain Dubai"],
        startingPrice: 100000,
        images: [
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?q=80&w=1000&auto=format&fit=crop"
        ]
    },

    // Switzerland
    {
        companyName: "Badrutt's Palace Hotel",
        destinations: ["St. Moritz", "Switzerland"],
        type: "Hotel",
        specializations: ["Alpine", "Luxury", "Winter"],
        budgetRange: { min: 80000, max: 400000 },
        rating: 5,
        description: "A legendary hotel in St. Moritz, Badrutt's Palace Hotel has been a landmark in the center of the village since 1896. It offers breathtaking views of the Engadin Alps and Lake St. Moritz.",
        amenities: ["Palace Wellness", "King's Social House", "Ice Rink", "Private Ski School", "Rolls-Royce Transfers"],
        sightSeeing: ["Lake St. Moritz", "Corviglia Ski Area", "Segantini Museum"],
        startingPrice: 95000,
        images: [
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1483095348487-53dbf97d8d5b?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "The Dolder Grand",
        destinations: ["Zurich", "Switzerland"],
        type: "Hotel",
        specializations: ["City Resort", "Wellness"],
        budgetRange: { min: 60000, max: 300000 },
        rating: 4,
        description: "The Dolder Grand provides the perfect environment for people who are looking for pleasure, exclusivity and relaxation: 175 luxurious rooms and suites, fine dining, a spa covering 4,000 square metres.",
        amenities: ["Award-winning Spa", "Art Collection", "Golf Course", "Fine Dining", "Limousine Service"],
        sightSeeing: ["Lake Zurich", "Bahnhofstrasse", "Old Town"],
        startingPrice: 70000,
        images: [
            "https://images.unsplash.com/photo-1562790351-d273a961e05b?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1561501900-3701fa6a0864?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Bürgenstock Hotel & Alpine Spa",
        destinations: ["Lucerne", "Switzerland"],
        type: "Hotel",
        specializations: ["Wellness", "Views"],
        budgetRange: { min: 100000, max: 500000 },
        rating: 5,
        description: "Perched 500 metres above Lake Lucerne, the Bürgenstock Hotel & Alpine Spa offers modern comfort and Swiss tradition. The resort is a masterpiece of modern architecture.",
        amenities: ["Alpine Spa", "Infinity Edge Pool", "Private Cinema", "Tennis Courts", "Funicular Railway"],
        sightSeeing: ["Hammetschwand Lift", "Lake Lucerne Cruise", "Chapel Bridge"],
        startingPrice: 110000,
        images: [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1000&auto=format&fit=crop"
        ]
    },

    // Others
    {
        companyName: "Aman Tokyo",
        destinations: ["Tokyo", "Japan"],
        type: "Hotel",
        specializations: ["Urban", "Zen"],
        budgetRange: { min: 120000, max: 400000 },
        rating: 5,
        description: "Occupying the top six floors of the Otemachi Tower, Aman Tokyo is an urban sanctuary high above the atmospheric whirl of tradition and modernity that defines Tokyo.",
        amenities: ["Aman Spa", "Wine Cellar", "Cigar Lounge", "Library", "Indoor Pool"],
        sightSeeing: ["Imperial Palace", "Ginza District", "Senso-ji Temple"],
        startingPrice: 130000,
        images: [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1493997181344-712f2f19dcf1?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Marina Bay Sands",
        destinations: ["Singapore"],
        type: "Hotel",
        specializations: ["Iconic", "City"],
        budgetRange: { min: 40000, max: 200000 },
        rating: 4,
        description: "Marina Bay Sands is an integrated resort fronting Marina Bay in Singapore. The resort includes a hotel, a convention-exhibition centre, a mall, a museum, a theatre, celebrity chef restaurants and the world's largest atrium casino.",
        amenities: ["Infinity Pool", "SkyPark", "Casino", "ArtScience Museum", "Shopping Mall"],
        sightSeeing: ["Gardens by the Bay", "Merlion Park", "Singapore Flyer"],
        startingPrice: 50000,
        images: [
            "https://images.unsplash.com/photo-1565967511849-76a60a516170?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Grace Hotel, Auberge Resorts Collection",
        destinations: ["Santorini", "Greece"],
        type: "Hotel",
        specializations: ["Romance", "Views"],
        budgetRange: { min: 80000, max: 300000 },
        rating: 4.9,
        description: "Grace Hotel Santorini is an exclusive boutique hotel in Santorini, Greece, perched above the world-famous Caldera with breathtaking views and sumptuous sunsets.",
        amenities: ["Infinity Pool", "Champagne Lounge", "Yoga & Pilates", "In-room Dining", "Concierge"],
        sightSeeing: ["Oia Sunset", "Red Beach", "Ancient Thera"],
        startingPrice: 90000,
        images: [
            "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?q=80&w=1000&auto=format&fit=crop"
        ]
    },
    {
        companyName: "Four Seasons Resort Bora Bora",
        destinations: ["Bora Bora", "French Polynesia"],
        type: "Hotel",
        specializations: ["Tropical", "Honeymoon"],
        budgetRange: { min: 150000, max: 600000 },
        rating: 5.0,
        description: "Wrap yourself in the luxury of Four Seasons Resort Bora Bora, a sand-fringed idyll in the shadow of Mount Otemanu. Toast sunsets from your private plunge pool, marvel at the Tahitian night sky.",
        amenities: ["Overwater Bungalows", "Lagoon Sanctuary", "Te Mahana Spa", "Tennis Courts", "Kids for All Seasons"],
        sightSeeing: ["Mount Otemanu", "Matira Beach", "Coral Gardens"],
        startingPrice: 170000,
        images: [
            "https://images.unsplash.com/photo-1537905569824-f89f14cceb68?q=80&w=1000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?q=80&w=1000&auto=format&fit=crop"
        ]
    }
];